# Generated by Django 4.0.5 on 2022-07-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='time',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
