# Generated by Django 4.0.5 on 2022-07-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='left',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='right',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
