# Generated by Django 4.0.5 on 2022-07-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_left_account_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
